version: '3.8'

services:
  moviepy-generator:
    build: .
    ports:
      - "8080:8080"
    environment:
      - VIDEO_OUTPUT_DIR=/app/videos
      - MAX_WORKERS=2
      - MAX_VIDEO_DURATION=300
      - TEMP_DIR=/app/temp
    volumes:
      - ./videos:/app/videos
      - ./temp:/app/temp
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '2.0'
        reservations:
          memory: 1G
          cpus: '0.5'

  # Optional: Redis for caching (future enhancement)
  # redis:
  #   image: redis:7-alpine
  #   restart: unless-stopped
  #   volumes:
  #     - redis_data:/data

# volumes:
#   redis_data: